from django.contrib import admin
from reg.models import *
admin.site.register(User)
# Register your models here.
#admin.site.register(Workshop)
#admin.site.register(Enrolled)
admin.site.register(Upcoming_events)
#admin.site.register(Offline_course)
#admin.site.register(Offline_description)
admin.site.register(Online_branch)
admin.site.register(Online_course)
#admin.site.register(Institutes)
#admin.site.register(Internship)
admin.site.register(Online_course_video)
#admin.site.register(Mentorship)
admin.site.register(Newsletter)
#admin.site.register(Test_categories)
#admin.site.register(Categories_dept)
#admin.site.register(Test_series)
#admin.site.register(Sample_test)
#admin.site.register(Sample_test_response)
#admin.site.register(Sample_test_result)
#admin.site.register(Question)
#admin.site.register(Answer)